from chatnoir_api import Index

DEFAULT_START = 0
DEFAULT_SIZE = 10
DEFAULT_SLOP = 0
DEFAULT_INDEX = {
    Index.ClueWeb09,
    Index.ClueWeb12,
}
DEFAULT_MINIMAL = False
DEFAULT_EXPLAIN = False
DEFAULT_EXTENDED_META = False
DEFAULT_RETRIES = 5
DEFAULT_BACKOFF_SECONDS = 1
DEFAULT_STAGING = False
